### PR TITLE
feat: support for CommonJS

### PR DESCRIPTION
**Pull request by zfben**
Just support for used in CommonJS project.

### CODE REVIEW

**Comment by acutmore** [comment]
Hi @zfben! Thanks for your interest in `ts-blank-space` 😀

So far we have been happy with this package being ESM only. Especially with the latest versions of Node now directly supporting `require` of ESM ([1](https://joyeecheung.github.io/blog/2024/03/18/require-esm-in-node-js/), [2](https://nodejs.org/en/blog/release/v23.0.0#requireesm-is-now-enabled-by-default)) we are rapidly heading towards a world where dual publishing CJS+ESM has fewer benefits.

The places within Bloomberg where we have needed to use `ts-blank-space` from an older Node project we have been able to use `await import("ts-blank-space")`. Perhaps others will be able to do the same?

**Comment by zfben** [comment]
Thanks @acutmore, but in my case, I need to execute ts-blank-space synchronously. The await import is asynchronous. However, I'm glad to learn that Node.js 23 will resolve this issue, but currently my project is still using an older version of Node.js.

**Comment by acutmore** [comment]
>  I need to execute ts-blank-space synchronously

Would you be able to go into more details? Perhaps there could be another solution. Module loading tends to only be synchronous for commonJS, but `ts-blank-space` doesn't supports TypeScript's CJS syntax (`import =` and `export =`) ([docs](https://github.com/bloomberg/ts-blank-space/blob/main/docs/unsupported_syntax.md#runtime-impacting-syntax)).

> I'm glad to learn that Node.js 23 will resolve this issue

I believe this will also be back ported to Node 22, which will soon be the active Node version with Node 20 going into maintenance mode: https://nodejs.org/en/about/previous-releases#release-schedule

Adding a CJS build adds complexity to this project. The full set of dev packages to install goes from 4 to 162 because `tsup` has a large subtree of packages. We'll also need to add more than just `tsup` to the build, running `npm pack` and passing the result to https://arethetypeswrong.github.io it says that there are no type declarations for the CJS export.

**Comment by zfben** [comment]
@acutmore I'm currently using SWC to handle the synchronous transformation issue. Indeed, tsup has too many dependencies, and since the stable version next year will support synchronous imports, I don't think we need to rush to solve this problem now.

**Pull request closed without merging**
